---
name: ItemDropText
version: 0.0.2
main: NhanAZ\ItemDropText\Main
api: 4.1.0

website: https://github.com/NhanAZ
description: Displays floating text that contains information of the dropped item.
author: NhanAZ
...
