---
# - \n : Newlines.
# - & or ยง : Colors.
# - {name} : Returns the name of the item, or the custom name if it is set.
# - {vanillaName} : Returns the vanilla name of the item, disregarding custom names.
# - {count} : Returns the count of the item.
# - {attackPoints} : Returns how many points of damage this item will deal to an entity when used as a weapon.
# - {cooldownTicks} : Returns the number of ticks a player must wait before activating this item again.
# - {defensePoints} : Returns how many armor points can be gained by wearing this item.
# - {maxStackSize} : Returns the highest amount of this item which will fit into one inventory slot.
# - {lore} : Returns the lore of the item.
# - {despawnDelay} : Returns the number of time left before this item will despawn.
format: "{name} x{count}"
...
